package FoodAccounting;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author satil
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
                this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        NombreDelProyecto = new javax.swing.JLabel();
        WelcomeBack = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        TextoEmail1 = new javax.swing.JTextField();
        Email1 = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        PasswordRecovery = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        Background.setBackground(new java.awt.Color(255, 0, 153));
        Background.setMinimumSize(new java.awt.Dimension(800, 500));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombreDelProyecto.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        NombreDelProyecto.setText("FoodAccounting");
        Background.add(NombreDelProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 230, 40));

        WelcomeBack.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        WelcomeBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeBack.setText("Welcome Back");
        Background.add(WelcomeBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 380, 70));

        Email.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Email.setText("Password");
        Background.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        TextoEmail1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        TextoEmail1.setForeground(new java.awt.Color(153, 153, 153));
        TextoEmail1.setText("Enter your email address");
        TextoEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoEmail1ActionPerformed(evt);
            }
        });
        Background.add(TextoEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 420, 40));

        Email1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Email1.setText("Email");
        Background.add(Email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        PasswordField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PasswordField.setForeground(new java.awt.Color(153, 153, 153));
        PasswordField.setText("jPasswordField1");
        Background.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 420, 40));

        PasswordRecovery.setText("Forgot your password?");
        Background.add(PasswordRecovery, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 130, 20));

        jButton1.setBackground(new java.awt.Color(45, 32, 32));
        jButton1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Background.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 420, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextoEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoEmail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoEmail1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    MainMenu ventana = new MainMenu();
    ventana.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Email1;
    private javax.swing.JLabel NombreDelProyecto;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordRecovery;
    private javax.swing.JTextField TextoEmail1;
    private javax.swing.JLabel WelcomeBack;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
